version: '3.9'
services:
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - redis:/data
  # node-app:
  #   depends_on:
  #     - redis
  #   build: .
  #   ports:
  #     - "4444:4444"
  #   environment:
  #     NODE_ENV: production
  #     REDIS_HOST: cache
  #     REDIS_PORT: 6379
volumes:
  redis:
    driver: local